2021-02-06 06:24:31,976 INFO    MainThread:6195 [wandb_setup.py:_flush():70] setting env: {}
2021-02-06 06:24:31,976 INFO    MainThread:6195 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-06 06:24:31,976 INFO    MainThread:6195 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-06 06:24:31,976 INFO    MainThread:6195 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-06 06:24:31,976 INFO    MainThread:6195 [wandb_init.py:_log_setup():318] Logging user logs to /home/iiitd/Desktop/Ahmad/doa1/wandb/run-20210206_062431-mdrlni85/logs/debug.log
2021-02-06 06:24:31,977 INFO    MainThread:6195 [wandb_init.py:_log_setup():319] Logging internal logs to /home/iiitd/Desktop/Ahmad/doa1/wandb/run-20210206_062431-mdrlni85/logs/debug-internal.log
2021-02-06 06:24:34,417 INFO    MainThread:6195 [wandb_run.py:_console_start():1308] atexit reg
2021-02-06 06:24:34,417 INFO    MainThread:6195 [wandb_run.py:_redirect():1175] redirect: SettingsConsole.REDIRECT
2021-02-06 06:24:34,418 INFO    MainThread:6195 [wandb_run.py:_redirect():1178] Redirecting console.
2021-02-06 06:24:34,418 INFO    MainThread:6195 [redirect.py:install():205] install start
2021-02-06 06:24:34,418 INFO    MainThread:6195 [redirect.py:install():220] install stop
2021-02-06 06:24:34,418 INFO    MainThread:6195 [redirect.py:install():205] install start
2021-02-06 06:24:34,418 INFO    MainThread:6195 [redirect.py:install():220] install stop
2021-02-06 06:24:34,418 INFO    MainThread:6195 [wandb_run.py:_redirect():1222] Redirects installed.
2021-02-06 06:27:01,334 INFO    MainThread:6195 [wandb_run.py:_atexit_cleanup():1278] got exitcode: 1
2021-02-06 06:27:01,335 INFO    MainThread:6195 [wandb_run.py:_restore():1250] restore
2021-02-06 06:27:01,335 INFO    MainThread:6195 [redirect.py:uninstall():224] uninstall start
2021-02-06 06:27:01,335 INFO    MainThread:6195 [redirect.py:_stop():279] _stop: stdout
2021-02-06 06:27:01,335 INFO    stdout    :6195 [redirect.py:_pipe_relay():121] relay done saw last write: stdout
2021-02-06 06:27:01,335 INFO    stdout    :6195 [redirect.py:_pipe_relay():137] relay done done: stdout
2021-02-06 06:27:01,335 INFO    MainThread:6195 [redirect.py:_stop():285] _stop closed: stdout
2021-02-06 06:27:01,336 INFO    MainThread:6195 [redirect.py:_stop():291] _stop joined: stdout
2021-02-06 06:27:01,336 INFO    MainThread:6195 [redirect.py:_stop():293] _stop rd closed: stdout
2021-02-06 06:27:01,336 INFO    MainThread:6195 [redirect.py:uninstall():228] uninstall done
2021-02-06 06:27:01,336 INFO    MainThread:6195 [redirect.py:uninstall():224] uninstall start
2021-02-06 06:27:01,336 INFO    MainThread:6195 [redirect.py:_stop():279] _stop: stderr
2021-02-06 06:27:01,336 INFO    stderr    :6195 [redirect.py:_pipe_relay():121] relay done saw last write: stderr
2021-02-06 06:27:01,337 INFO    stderr    :6195 [redirect.py:_pipe_relay():137] relay done done: stderr
2021-02-06 06:27:01,337 INFO    MainThread:6195 [redirect.py:_stop():285] _stop closed: stderr
2021-02-06 06:27:01,337 INFO    MainThread:6195 [redirect.py:_stop():291] _stop joined: stderr
2021-02-06 06:27:01,337 INFO    MainThread:6195 [redirect.py:_stop():293] _stop rd closed: stderr
2021-02-06 06:27:01,337 INFO    MainThread:6195 [redirect.py:uninstall():228] uninstall done
2021-02-06 06:27:01,656 INFO    MainThread:6195 [wandb_run.py:_wait_for_finish():1395] got exit ret: uuid: "4d18410946f043cb980c599f1630a934"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 511
      total_bytes: 511
    }
  }
}

2021-02-06 06:27:03,660 INFO    MainThread:6195 [wandb_run.py:_wait_for_finish():1395] got exit ret: uuid: "86d2b5cd4d3845c19c2e06d5ef93ed06"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 7666
      total_bytes: 7666
    }
  }
}

2021-02-06 06:27:04,891 INFO    MainThread:6195 [wandb_run.py:_show_files():1614] logging synced files
2021-02-06 06:27:04,892 INFO    MainThread:6195 [internal.py:handle_exit():139] Internal process exited
